### @host = https://test.ahdis.ch/r4
@host = http://localhost:8080/r4


GET {{host}}/metadata HTTP/1.1
Accept: application/fhir+xml


### 1. POST Alis43ToBundle.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./input/maps/Alis43ToBundle.map

### 2. transform
POST {{host}}/StructureMap/$transform?source=http://fhir.ch/ig/ch-alis/StructureMap/Alis43ToBundle
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./input/images/AlisExampleComplete43.xml